/* 插入字典总表[PLAYER_LOGIN_METHOD-登陆方式] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('PLAYER_LOGIN_METHOD','登陆方式','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_LOGIN_METHOD','0·','邮箱注册','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_LOGIN_METHOD','1','手机号注册','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_LOGIN_METHOD','2','微信接入','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_LOGIN_METHOD','3','QQ接入','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_LOGIN_METHOD','4','游客登陆','','哇我真的懒得做游客模式',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_LOGIN_METHOD','5','Game Center登陆','','来点apple开发者',1);

/* 插入字典总表[PLAYER_PURCHASE_STATUS-支付状态] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('PLAYER_PURCHASE_STATUS','支付状态','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_STATUS','0','下单完成','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_STATUS','1','支付完成','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_STATUS','2','订单失败','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_STATUS','3','订单取消','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_STATUS','4','订单完成','','',1);

/* 插入字典总表[PLAYER_PURCHASE_CHANNEL-支付渠道] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('PLAYER_PURCHASE_CHANNEL','支付渠道','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_CHANNEL','0','银行直转','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_CHANNEL','1','微信支付','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_CHANNEL','2','支付宝支付','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_PURCHASE_CHANNEL','3','PayPal支付','','',1);

/* 插入字典总表[PLAYER_ACTION_LOG-玩家行为] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','玩家行为','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','-1','账户封禁','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','0','登陆','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','1','登出','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','2','注册账户','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','3','删除账户','','此条以前的不可删除，需留为日志',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','4','商店购买','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','5','内购信用点','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLAYER_ACTION_LOG','6','发送私信','','',1);

/* 插入字典总表[ROLE_MSG_STATUS-邮件状态] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('ROLE_MSG_STATUS','邮件状态','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_MSG_STATUS','0','已保存','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_MSG_STATUS','1','已发送','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_MSG_STATUS','2','已读','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_MSG_STATUS','3','附件已领取','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_MSG_STATUS','4','已删除','','',1);

/* 插入字典总表[ROLE_ITEM-玩家可持有物品] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('ROLE_ITEM','玩家可持有物品','使用三个char和三个short类型拼接在一起就足够存储，即1+1+1+4+4+4 = 15Bytes = 1 * long',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','1','carrier_slot','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','2','ship_slot','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','3','planet_slot','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','4','red_artifact','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','10','F_mk2_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','11','C_mk2_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','12','B_mk2_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','13','I_mk2_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','14','F_mk3_blueprint','','mk3战机似乎过于昂贵且过于op，不值得出',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','15','C_mk3_blueprint','','这个倒是能出一出',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','16','B_mk3_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','17','I_mk3_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','20','Carrier_mk2_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','21','Carrier_mk3_blueprint','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','30','universal_researchpoint','','所有全局科研项统一定价涨幅：10元/级',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','31','void_crystal','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','40','yellow_artifact','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','41','blue_artifact','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_ITEM','42','fleet_slot','','',1);

/* 插入字典总表[TYPE_PLANET-星球种类] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('TYPE_PLANET','星球种类','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','0','oceanic','','海洋星球',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','1','icy','','极地星球',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','2','volcanic','','熔岩星球',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','3','rocky','','岩石星球',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','4','desert','','荒漠星球',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','5','jungle','','丛林星球',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','6','red_cit','','红色堡垒',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','7','yellow_cit','','黄色堡垒',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','8','blue_cit','','蓝色堡垒',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_PLANET','9','fractured','','破碎星球',1);

/* 插入字典总表[TYPE_SYSTEM-星系种类] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('TYPE_SYSTEM','星系种类','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','0','pink','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','1','red','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','2','orange','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','3','yellow','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','4','lime','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','5','green','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','6','water','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','7','blue','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','8','purple','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','9','white','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TYPE_SYSTEM','10','black_hole','','',1);

/* 插入字典总表[ROLE_RACE-角色种族] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('ROLE_RACE','角色种族','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','00','terran m','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','01','terran f','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','10','vossk m','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','11','vossk f','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','20','nivelian m','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','21','vivelian f','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','30','void m','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_RACE','31','void f','','',1);

/* 插入字典总表[ROLE_PRIVILIGE-权限组] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('ROLE_PRIVILIGE','权限组','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_PRIVILIGE','0','player','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_PRIVILIGE','1','NPC','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ROLE_PRIVILIGE','2','GM','','',1);

/* 插入字典总表[PLANET_STRUCTURE-建筑] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('PLANET_STRUCTURE','建筑','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','0','None','','无建筑',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','1','Headquarter','','HQ',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','2','Ore Miner','','金属厂',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','3','Gas Vapourizer','','气体厂',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','4','Crystal Refinary','','晶体厂',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','5','Shipyard','','造船厂',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','6','Barracks','','兵营',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','7','Scan Radar Array','','雷达',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','8','Laboratory','','实验室',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','9','Trade Center','','贸易站+仓库',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','10','Planet Defense Shield','','星盾',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','11','Citadel','','神石堡垒',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('PLANET_STRUCTURE','12','Gravity Well Amplifier','','重力井增幅器',1);

/* 插入字典总表[CARRIER_TYPE-航母型号] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('CARRIER_TYPE','航母型号','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_TYPE','0','mk1','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_TYPE','1','mk2','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_TYPE','2','mk3','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_TYPE','3','void','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_TYPE','4','battle_cruiser','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_TYPE','5','gravity_interceptor','','',1);

/* 插入字典总表[CARRIER_UPGRADE_ITEM-航母升级项] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('CARRIER_UPGRADE_ITEM','航母升级项','规定JSON格式用，不作为枚举直接插入到库中',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_UPGRADE_ITEM','0','red_stone','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_UPGRADE_ITEM','1','yellow_stone','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_UPGRADE_ITEM','2','blue_stone','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('CARRIER_UPGRADE_ITEM','3','gravity_well_amplifier','','',1);

/* 插入字典总表[TASKFORCE_TASKS-特混舰队任务种类] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('TASKFORCE_TASKS','特混舰队任务种类','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TASKFORCE_TASKS','0','assign','','重新安置',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TASKFORCE_TASKS','1','deliver','','运输',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TASKFORCE_TASKS','2','attack','','进攻',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TASKFORCE_TASKS','3','mission','','雷达任务',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TASKFORCE_TASKS','4','colonize','','殖民',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('TASKFORCE_TASKS','5','blockade','','区域拦截',1);

/* 插入字典总表[SHIP_TYPE-舰载机型号] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('SHIP_TYPE','舰载机型号','想到个新玩法：实验室可以装备多战机编队科技（数值上是蚊子腿），只要实验室在控制之中，就在每次作战中都生效。某次作战中投入的某型战机数量如果恰逢单编队战机数量的整数倍（Eg:学习6战斗机编队战术后，某次作战中投入36架战斗机），则该部分战机享受攻击和防御加成，额外的第37-41架则不享受。核心用意是鼓励玩家走出安全区，开发稳定的根据地。',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','0','F_mk1','','战斗机',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','1','C_mk1','','运输机',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','2','B_mk1','','轰炸机',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','3','I_mk1','','拦截机',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','4','F_mk2','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','5','C_mk2','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','6','B_mk2','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','7','I_mk2','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','8','F_mk3','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','9','C_mk3','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','10','B_mk3','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('SHIP_TYPE','11','I_mk3','','',1);

/* 插入字典总表[ALLIANCE_RELATION-联盟关系] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('ALLIANCE_RELATION','联盟关系','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_RELATION','0','neutral','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_RELATION','1','non-aggressive','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_RELATION','2','enemy','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_RELATION','3','NPC','','',1);

/* 插入字典总表[ALLIANCE_MEMBER_RANK-联盟成员军阶表] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('ALLIANCE_MEMBER_RANK','联盟成员军阶表','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_MEMBER_RANK','0','member','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_MEMBER_RANK','1','senior_member','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_MEMBER_RANK','2','officer','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_MEMBER_RANK','3','senior_officer','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_MEMBER_RANK','4','leader','','',1);

/* 插入字典总表[ALLIANCE_PERMISSION_LV-联盟许可等级] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('ALLIANCE_PERMISSION_LV','联盟许可等级','指报名加入的许可等级',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_PERMISSION_LV','0','by_SO','','default, 经高管许可',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_PERMISSION_LV','1','by_ldr','','严格，经首领许可',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_PERMISSION_LV','2','by_O','','宽松，经军官许可',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('ALLIANCE_PERMISSION_LV','3','closed','','不允许加入',1);

/* 插入字典总表[MAIL_STATUS-私信邮件状态] */
INSERT INTO SYS_DICT(KEY_,LABEL,INTRO,REVISION) VALUES('MAIL_STATUS','私信邮件状态','',1);
/* 插入字典明细表 */
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('MAIL_STATUS','0','已发送','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('MAIL_STATUS','1','已读','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('MAIL_STATUS','2','已删除','','',1);
INSERT INTO SYS_DICT_ITEM(DICT_KEY,KEY_,LABEL,SORT_,INTRO,REVISION) VALUES('MAIL_STATUS','3','提交举报','','',1);

